services:
  app:
    build:
      context: ./
      target: production
    environment:
      - DUMMY_ENV_VARIABLE=1
      # add environment-specific variables as required
    ports:
      - "${PORT-3000}:80" # 3000 by default - can be changed in .env file